import type { BorrowAsset } from './borrow-flow.types';

export const borrowAssets: BorrowAsset[] = [
  {
    id: 'btc',
    symbol: 'BTC',
    name: 'Bitcoin',
    subtitle: 'Bitcoin',
    iconSrc: '/coins/btc.svg',
    price: '$65,000',
    change: '6.12%',
    direction: 'down',
    accentColor: '#F7931A',
    network: 'Bitcoin',
    borrowApy: '5.23%',
    walletBalanceLabel: 'BTC Balance',
    availableAmountText: 'Available amount: 0.80 BTC',
    availableCollateral: 0.8,
    minimumCollateral: 0.06,
    collateralToken: 'BTC',
    estimatedReceive: '1.00',
    estimatedReceiveValue: '20,000.00 Naira',
  },
  {
    id: 'eth',
    symbol: 'ETH',
    name: 'Ethereum',
    subtitle: 'Ethereum',
    iconSrc: '/coins/eth.svg',
    price: '$2,500',
    change: '6.12%',
    direction: 'up',
    accentColor: '#627EEA',
    network: 'Ethereum',
    borrowApy: '6.43%',
    walletBalanceLabel: 'Eth Balance',
    availableAmountText: 'Available amount: 0.05 ETH',
    availableCollateral: 0.05,
    minimumCollateral: 0.06,
    collateralToken: 'ETH',
    estimatedReceive: '2000.00',
    estimatedReceiveValue: '1 ETH',
  },
  {
    id: 'sol',
    symbol: 'SOL',
    name: 'Solana',
    subtitle: 'Solana',
    iconSrc: '/coins/sol.svg',
    price: '$70',
    change: '6.12%',
    direction: 'down',
    accentColor: '#8B5CF6',
    network: 'Solana',
    borrowApy: '6.12%',
    walletBalanceLabel: 'SOL Balance',
    availableAmountText: 'Available amount: 0.20 SOL',
    availableCollateral: 0.2,
    minimumCollateral: 0.06,
    collateralToken: 'SOL',
    estimatedReceive: '200.00',
    estimatedReceiveValue: '1 SOL',
  },
  {
    id: 'usdt',
    symbol: 'USDT',
    name: 'Tether',
    subtitle: 'Tether',
    iconSrc: '/coins/usdt.svg',
    price: '$1',
    change: '6.12%',
    direction: 'up',
    accentColor: '#26A17B',
    network: 'Ethereum',
    borrowApy: '4.86%',
    walletBalanceLabel: 'USDT Balance',
    availableAmountText: 'Available amount: 850 USDT',
    availableCollateral: 850,
    minimumCollateral: 100,
    collateralToken: 'USDT',
    estimatedReceive: '850.00',
    estimatedReceiveValue: '850.00 USDT',
  },
  {
    id: 'usdc',
    symbol: 'USDC',
    name: 'USD Coin',
    subtitle: 'USDC',
    iconSrc: '/coins/usdc.svg',
    price: '$1',
    change: '6.12%',
    direction: 'up',
    accentColor: '#2775CA',
    network: 'Solana',
    borrowApy: '4.72%',
    walletBalanceLabel: 'USDC Balance',
    availableAmountText: 'Available amount: 600 USDC',
    availableCollateral: 600,
    minimumCollateral: 100,
    collateralToken: 'USDC',
    estimatedReceive: '600.00',
    estimatedReceiveValue: '600.00 USDC',
  },
];